# Generated by Django 4.0 on 2022-01-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
