# Generated by Django 4.0 on 2022-01-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_rename_author_id_books_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publisher',
            new_name='publisher_id',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
